-- Generated by Lava 2000

use work.all;

entity
  copy
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; inp : in bit

  -- outputs
  ; outp_0 : out bit
  ; outp_1 : out bit
  );
end entity copy;

architecture
  structural
of
  copy
is
  signal w1 : bit;
begin
  c_w1      : entity id    port map (clk, inp, w1);

  -- naming outputs
  c_outp_0  : entity id    port map (clk, w1, outp_0);
  c_outp_1  : entity id    port map (clk, w1, outp_1);
end structural;
