-- Generated by Lava 2000

use work.all;

entity
  par
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; a : in bit
  ; b : in bit

  -- outputs
  ; c : out bit
  ; d : out bit
  );
end entity par;

architecture
  structural
of
  par
is
  signal w1 : bit;
  signal w2 : bit;
  signal w3 : bit;
  signal w4 : bit;
begin
  c_w2      : entity id    port map (clk, a, w2);
  c_w1      : entity inv   port map (clk, w2, w1);
  c_w4      : entity id    port map (clk, b, w4);
  c_w3      : entity inv   port map (clk, w4, w3);

  -- naming outputs
  c_c       : entity id    port map (clk, w1, c);
  c_d       : entity id    port map (clk, w3, d);
end structural;
