-- Generated by Lava 2000

use work.all;

entity
  sum3Bit
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; carryIn : in bit
  ; a0 : in bit
  ; a1 : in bit
  ; a2 : in bit
  ; b0 : in bit
  ; b1 : in bit
  ; b2 : in bit

  -- outputs
  ; sum0 : out bit
  ; sum1 : out bit
  ; sum2 : out bit
  ; carryOut : out bit
  );
end entity sum3Bit;

architecture
  structural
of
  sum3Bit
is
  signal w1 : bit;
  signal w2 : bit;
  signal w3 : bit;
  signal w4 : bit;
  signal w5 : bit;
  signal w6 : bit;
  signal w7 : bit;
  signal w8 : bit;
  signal w9 : bit;
  signal w10 : bit;
  signal w11 : bit;
  signal w12 : bit;
  signal w13 : bit;
  signal w14 : bit;
  signal w15 : bit;
  signal w16 : bit;
  signal w17 : bit;
  signal w18 : bit;
  signal w19 : bit;
  signal w20 : bit;
  signal w21 : bit;
  signal w22 : bit;
begin
  c_w2      : entity id    port map (clk, carryIn, w2);
  c_w4      : entity id    port map (clk, a0, w4);
  c_w5      : entity id    port map (clk, b0, w5);
  c_w3      : entity xor2  port map (clk, w4, w5, w3);
  c_w1      : entity xor2  port map (clk, w2, w3, w1);
  c_w8      : entity and2  port map (clk, w2, w3, w8);
  c_w9      : entity and2  port map (clk, w4, w5, w9);
  c_w7      : entity xor2  port map (clk, w8, w9, w7);
  c_w11     : entity id    port map (clk, a1, w11);
  c_w12     : entity id    port map (clk, b1, w12);
  c_w10     : entity xor2  port map (clk, w11, w12, w10);
  c_w6      : entity xor2  port map (clk, w7, w10, w6);
  c_w15     : entity and2  port map (clk, w7, w10, w15);
  c_w16     : entity and2  port map (clk, w11, w12, w16);
  c_w14     : entity xor2  port map (clk, w15, w16, w14);
  c_w18     : entity id    port map (clk, a2, w18);
  c_w19     : entity id    port map (clk, b2, w19);
  c_w17     : entity xor2  port map (clk, w18, w19, w17);
  c_w13     : entity xor2  port map (clk, w14, w17, w13);
  c_w21     : entity and2  port map (clk, w14, w17, w21);
  c_w22     : entity and2  port map (clk, w18, w19, w22);
  c_w20     : entity xor2  port map (clk, w21, w22, w20);

  -- naming outputs
  c_sum0    : entity id    port map (clk, w1, sum0);
  c_sum1    : entity id    port map (clk, w6, sum1);
  c_sum2    : entity id    port map (clk, w13, sum2);
  c_carryOut : entity id    port map (clk, w20, carryOut);
end structural;
